jobs:
  apk:
    name: Generate APK
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4.1.1
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: gradle
        check-latest: true
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Build debug APK
      run: bash ./gradlew assembleDev --stacktrace --no-configuration-cache
    - continue-on-error: true
      name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-dev-debug
        path: app/build/outputs/apk/dev/debug/app-dev-debug.apk
  lint:
    name: Lint
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4.1.1
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: gradle
        check-latest: true
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Lint
      run: bash ./gradlew lintDevDebug --stacktrace --no-configuration-cache
  test:
    name: Unit tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4.1.1
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: gradle
        check-latest: true
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Unit tests
      run: bash ./gradlew test --stacktrace --no-configuration-cache
  validation:
    name: Validate Gradle Wrapper
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4.1.1
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: gradle
        check-latest: true
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v2
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___android.yml
permissions:
  contents: read
