concurrency:
  cancel-in-progress: true
  group: sync-approve-${{ github.head_ref || github.run_id }}
jobs:
  auto-approve:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'sync') && github.actor
      == 'nextcloud-android-bot' }}
    name: Auto approve sync
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
name: Auto approve sync
on:
  repository_dispatch:
    types: trigger-ga___autoApproveSync.yml
permissions:
  pull-requests: write
