concurrency:
  cancel-in-progress: true
  group: dependabot-approve-${{ github.head_ref || github.run_id }}
jobs:
  auto-approve:
    if: github.actor == 'dependabot[bot]'
    name: Auto approve dependabot
    permissions:
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
name: Auto approve dependabot
on:
  repository_dispatch:
    types: trigger-ga___autoApproveDependabot.yml
permissions:
  contents: read
