concurrency:
  cancel-in-progress: true
  group: detect-new-java-files-${{ github.head_ref || github.run_id }}
jobs:
  detectNewJavaFiles:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: file_changes
      uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
      with:
        output: ','
    - continue-on-error: true
      name: Detect new java files
      run: "if [ -z '${{ steps.file_changes.outputs.files_added }}' ]; then\n    echo\
        \ \"No new files added\"\n    exit 0\nfi\nnew_java=$(echo '${{ steps.file_changes.outputs.files_added\
        \ }}' | tr ',' '\\n' | grep '\\.java$' | cat)\nif [ -n \"$new_java\" ]; then\n\
        \    # shellcheck disable=SC2016\n    printf 'New java files detected:\\n```\\\
        n%s\\n```\\n' \"$new_java\" | tee \"$GITHUB_STEP_SUMMARY\"\n    exit 1\nelse\n\
        \    echo \"No new java files detected\"\n    exit 0\nfi\n"
name: Detect new java files
on:
  repository_dispatch:
    types: trigger-ga___detectNewJavaFiles.yml
permissions: read-all
