jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      name: REUSE Compliance Check
      uses: fsfe/reuse-action@a46482ca367aef4454a87620aa37c2be4b2f8106
name: REUSE Compliance Check
on:
  repository_dispatch:
    types: trigger-ga___reuse.yml
