jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e
      with:
        days-before-close: 14
        days-before-pr-close: -1
        days-before-stale: 28
        exempt-all-pr-milestones: true
        exempt-issue-labels: no-stale
        labels-to-remove-when-unstale: needs info
        only-labels: bug,needs info
        stale-issue-message: This bug report did not receive an update in the last
          4 weeks. Please take a look again and update the issue with new details,
          otherwise the issue will be automatically closed in 2 weeks. Thank you!
name: Close stale issues
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
permissions: read-all
